baseURL = 'https://safe049.github.io/'
languageCode = 'zh'
title = 'Dysprosium'
theme = "hugo-theme-m10c"

sectionPagesMenu = 'main'

[markup.goldmark.renderer]
  unsafe = true
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
[params]
  author = "Dysprosium"
  description = "最好的描述就是没有描述"
  avatar = 'https://free.picui.cn/free/2025/12/13/693ce11828617.png'
  favicon = 'https://free.picui.cn/free/2025/12/13/693ce11828617.png'
  menu_item_separator = " | "
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/safe049"
  [[params.social]]
    icon = "mail"
    name = "Email"
    url = "mailto:1329261154@qq.com"
[params.utteranc]
  enable = true
  repo = "safe049/safe049.github.io" ##换成自己得
  issueTerm = "pathname"
  theme = "github-dark"
